### ISSUE TITLE
Use http API endpoint to avoid ssh issues with older python versions

### ISSUE THREAD

**Issue by msmole** [bitmovin/bitcodin-python#2]

**Comment by moser4035** [comment]
Implemeted in v1.2.6 Commit: https://github.com/bitmovin/bitcodin-python/commit/7ed35c5730ef701b9a091c1dbb2106c4a3d030ec

**Comment by jaap3** [comment]
I strongly disagree with this change. Don't downgrade a secure default just because people might be using an outdated version of python.

When using this library the chances are high that you are sending sensitive information, including secret API keys, usernames and passwords. All this information should be encrypted by default.

Instead you should:

 1. Strongly recommend people to upgrade to Python >= 2.7.9
 2. Link to http://urllib3.readthedocs.org/en/latest/security.html#installing-urllib3-with-sni-support-and-certificates as a work around for people that cannot upgrade
 3. And finally document that (as a last resort) users can manually set `bitcodin.api_base = 'http://portal.bitcodin.com/api'` with the note that this might result in sending API secrets and/or usernames/passwords completely unencrypted in plain text.
